In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset = pd.read_csv('bank_full.csv')

In [20]:
dataset

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [24]:
dataset=pd.get_dummies(dataset,columns=['job','marital','education','contact','poutcome','month'])

In [28]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   age                  45211 non-null  int64 
 1   default              45211 non-null  object
 2   balance              45211 non-null  int64 
 3   housing              45211 non-null  object
 4   loan                 45211 non-null  object
 5   day                  45211 non-null  int64 
 6   duration             45211 non-null  int64 
 7   campaign             45211 non-null  int64 
 8   pdays                45211 non-null  int64 
 9   previous             45211 non-null  int64 
 10  y                    45211 non-null  object
 11  job_admin.           45211 non-null  uint8 
 12  job_blue-collar      45211 non-null  uint8 
 13  job_entrepreneur     45211 non-null  uint8 
 14  job_housemaid        45211 non-null  uint8 
 15  job_management       45211 non-null  uint8 
 16  job_

In [37]:
x_d = pd.concat([dataset.iloc[:,0:10],dataset.iloc[:,11:]],axis=1)
y = dataset.iloc[:, 10].values

In [55]:
x_d['default'] = np.where(x_d['default'].str.contains("yes"), 1, 0)
x_d['housing'] = np.where(x_d['housing'].str.contains("yes"), 1, 0)
x_d['loan'] = np.where(x_d['loan'].str.contains("yes"), 1, 0)
x_d

age  default  balance  housing  loan  day  duration  campaign  pdays  \
0       58        0     2143        1     0    5       261         1     -1   
1       44        0       29        1     0    5       151         1     -1   
2       33        0        2        1     1    5        76         1     -1   
3       47        0     1506        1     0    5        92         1     -1   
4       33        0        1        0     0    5       198         1     -1   
...    ...      ...      ...      ...   ...  ...       ...       ...    ...   
45206   51        0      825        0     0   17       977         3     -1   
45207   71        0     1729        0     0   17       456         2     -1   
45208   72        0     5715        0     0   17      1127         5    184   
45209   57        0      668        0     0   17       508         4     -1   
45210   37        0     2971        0     0   17       361         2    188   

       previous  job_admin.  job_blue-collar  job_entrepreneur  job_housemaid  \
0             0           0                0                 0              0   
1             0           0                0                 0              0   
2             0           0                0                 1              0   
3             0           0                1                 0              0   
4             0           0                0                 0              0   
...         ...         ...              ...               ...            ...   
45206         0           0                0                 0              0   
45207         0           0                0                 0              0   
45208         3           0                0                 0              0   
45209         0           0                1                 0              0   
45210        11           0                0                 1              0   

       job_management  job_retired  job_self-employed  job_services  \
0                   1            0                  0             0   
1                   0            0                  0             0   
2                   0            0                  0             0   
3                   0            0                  0             0   
4                   0            0                  0             0   
...               ...          ...                ...           ...   
45206               0            0                  0             0   
45207               0            1                  0             0   
45208               0            1                  0             0   
45209               0            0                  0             0   
45210               0            0                  0             0   

       job_student  job_technician  job_unemployed  job_unknown  \
0                0               0               0            0   
1                0               1               0            0   
2                0               0               0            0   
3                0               0               0            0   
4                0               0               0            1   
...            ...             ...             ...          ...   
45206            0               1               0            0   
45207            0               0               0            0   
45208            0               0               0            0   
45209            0               0               0            0   
45210            0               0               0            0   

       marital_divorced  marital_married  marital_single  education_primary  \
0                     0                1               0                  0   
1                     0                0               1                  0   
2                     0                1               0                  0   
3                     0                1               0                  0   
4                     0         

In [56]:
x=x_d.values

In [58]:
print(x)

[[  58    0 2143 ...    0    0    0]
 [  44    0   29 ...    0    0    0]
 [  33    0    2 ...    0    0    0]
 ...
 [  72    0 5715 ...    1    0    0]
 [  57    0  668 ...    1    0    0]
 [  37    0 2971 ...    1    0    0]]


In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [60]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [61]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### Comparing actual result of y_train and y_pred which has predicted data from y_train dataset

In [63]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


### Confusion Matrix

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9847  131]
 [1134  191]]


0.8880828098734849